[package]
name = "bluetooth"
version = "0.1.0"
edition = "2021"


[dependencies]
btleplug = "0.10"  # Bluetooth library
tokio = { version = "1", features = ["full"] }  # Async runtime
log = "0.4"  # Logging
env_logger = "0.9"  # Logging setup
uuid = { version = "1.4", features = ["v4"] }

